# Generated by Django 4.2.2 on 2023-06-06 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=0)),
                ('ballot_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteStore.ballotbox')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteStore.contestant')),
            ],
        ),
        migrations.AddField(
            model_name='ballotbox',
            name='contestants',
            field=models.ManyToManyField(through='VoteStore.Vote', to='VoteStore.contestant'),
        ),
    ]
